#!/usr/bin/env bash
# script to install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
